In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("Combined_dataset.csv")

In [6]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [7]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [8]:
df.shape

(1000, 24)

In [9]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [10]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [11]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [12]:
df["discount"] = df["discount"].fillna(df["discount"].mean())

In [13]:
df["what_customers_said"] = df["what_customers_said"].fillna("No Review")

In [14]:
df["seller_name"] = df["seller_name"].fillna("Unknown")

In [15]:
df["videos"] = df["videos"].fillna("No Video")

In [16]:
df["seller_information"] = df["seller_information"].fillna("Unavailable")

In [17]:
df["variations"] = df["variations"].fillna("No Variations")

In [18]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [19]:
df[["title", "category", "final_price", "rating"]]

              title   category   final_price  rating
0       Lino Perros  backpacks   "₹3,995.00"     3.8
1    Tommy Hilfiger  backpacks   "₹2,899.00"     4.5
2             Lavie  backpacks   "₹2,999.00"     4.4
3            F Gear  backpacks   "₹1,675.00"     4.4
4         MYTRIDENT  bath-robe   "₹2,899.00"     4.7
..              ...        ...           ...     ...
995           KREDO    watches  "₹11,890.00"     3.5
996           GUESS    watches   "₹8,900.00"     5.0
997        GIORDANO    watches   "₹7,950.00"     2.8
998        Fastrack    watches   "₹2,636.00"     4.3
999         BOLDFIT  yoga-mats     "₹699.00"     3.8

[1000 rows x 4 columns]

In [20]:
df[df["rating"] > 4]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unavailable,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",No Review,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unavailable,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.000000,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",No Review,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.000000,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Unavailable,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,53.503982,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",No Video,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,2466414,Daniel Klein,Women Brown Analogue Watch DK11467-6,4.4,940,6950,53.000000,"""₹3,266.00""",INR,http://assets.myntassets.com/assets/images/246...,...,"{""1_star"":56,""2_stars"":21,""3_stars"":42,""4_star...",No Review,DES███ER ███GRE█████████IA ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Fir███Flo███ Pl█████████, I███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.000000,"""₹3,235.00""",INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.000000,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.000000,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.000000,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]",No Video,Sho███o. ███-10█████████enu███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [21]:
df["category"].unique()

<StringArray>
[              'backpacks',               'bath-robe',
    'bathroom-accessories',             'bath-towels',
               'bedsheets',                   'belts',
                'bodysuit',                   'boots',
                  'boxers',                     'bra',
                'bracelet',                  'briefs',
               'camisoles',          'candle-holders',
                    'caps',            'casual-shoes',
             'chair-cover',            'clothing-set',
                'clutches',                 'co-ords',
     'curtains-and-sheers',                 'cutlery',
              'dinnerware',                 'dresses',
              'duffel-bag',               'dungarees',
                 'dupatta',                'earrings',
          'ethnic-dresses',       'face-moisturisers',
  'face-wash-and-cleanser',                   'flats',
              'flip-flops',    'floor-mats--dhurries',
            'formal-shoes',              'foundation',
                  'gloves',          'hair-accessory',
     'hair-brush-and-comb',     'hair-cream-and-mask',
              'hair-masks',                'handbags',
              'headphones',                   'heels',
      'home-fragrance-set',         'innerwear-vests',
                 'jackets',                   'jeans',
                'jumpsuit',                  'kurtas',
              'kurta-sets',                  'kurtis',
                'lipstick',            'lounge-pants',
           'lounge-shorts',          'lounge-tshirts',
             'mangalsutra',      'mobile-accessories',
              'nightdress',             'night-suits',
           'outdoor-masks',                'palazzos',
   'perfume-and-body-mist',           'pillow-covers',
                    'ring',                 'runners',
                 'sandals',            'saree-blouse',
                  'sarees',                 'scarves',
 'shampoo-and-conditioner',      'shaving-essentials',
                'sherwani',                  'shirts',
                  'shorts',              'showpieces',
                  'skirts',            'sports-shoes',
              'sunglasses',                'sweaters',
             'sweatshirts',               'swim-tops',
            'table-covers',         'thermal-bottoms',
                  'tights',                    'tops',
               'towel-set',             'track-pants',
             'trolley-bag',                'trousers',
                   'trunk',                 'tshirts',
                  'tunics',                'wall-art',
                 'wallets',                 'watches',
               'yoga-mats']
Length: 97, dtype: str

In [22]:
df[df["category"] == "jeans"]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
374,18973692,Levis,Men Blue 65504 Skinny Fit Mid Rise Light Fade ...,4.2,426,4099,57.000000,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":44,""2_stars"":12,""3_stars"":26,""4_star...","[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973692_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
375,18973742,Levis,Men Blue Slim Fit Slash Knee Heavy Fade Stretc...,4.2,182,4399,48.000000,"""₹2,287.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":12,""2_stars"":9,""3_stars"":19,""4_stars...","[{""percentage"":""56"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973742_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
376,19008522,Calvin Klein Jeans,Women Straight Fit Pure Cotton Jeans,3.8,14,7999,20.000000,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Pla███um ███hio███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-19008522_cae700"",""https://videos.myntasse...",1ST███OOR███O 5█████████MAH███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
377,18974084,Levis,512 Men Navy Blue Slim Tapered Fit Mid-Rise Li...,4.2,135,4399,57.000000,"""₹1,891.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":11,""2_stars"":4,""3_stars"":14,""4_stars...","[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Video,Eco███xpr███ Pv█████████no ███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
378,18873126,KETCH,Men Charcoal Slim Fit Clean Look Light Fade St...,4.0,20,1749,64.000000,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",No Video,Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
379,18826658,Chemistry,Women Navy Blue Casual Jeans,3.7,15,1899,55.000000,"""₹854.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Che███try███sig█████████ Li██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Video,"God███ No███,8,█████████ldi███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
380,18960426,Lee,Men Blue Rodeo Straight Fit Low Distress Heavy...,3.9,42,3799,55.000000,"""₹1,709.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Fla███tar███mme██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Video,"1st███oor███abi█████████02,███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
381,18802522,BEAT LONDON by PEPE JEANS,Men Tapered Fit Low-Rise Heavy Fade Stretchabl...,4.0,20,2799,50.000000,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",Plo███o- ███ 1s█████████Sui███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
382,18973648,Levis,Men Blue 511 Slim Fit Light Fade Stretchable J...,4.2,290,4099,53.503982,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":25,""2_stars"":7,""3_stars"":17,""4_stars...","[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973648_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,No Variations,"{""best_price"":""3689"",""coupon_code"":""NORETURNS1...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
383,18973888,Levis,Men Skinny Fit Heavy Fade Stretchable Jeans,4.4,333,4099,53.503982,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":26,""2_stars"":1,""3_stars"":11,""4_stars...","[{""percentage"":""74"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973888_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
384,18973730,Levis,Men Blue 511 Slim Fit Mid Rise Light Fade Stre...,4.1,193,4399,49.000000,"""₹4,399.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":22,""2_stars"":9,""3_stars"":9,""4_stars""...","[{""percentage"":""58"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973730_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
385,18973948,Levis,Men Blue 512 Slim Tapered Fit Stretchable Jeans,4.0,30,4999,30.000000,"""₹3,499.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":5,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
386,19008496,Calvin Klein Jeans,Women Skinny Fit High-Rise Light Fade Stretcha...,5.0,8,7999,40.000000,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Pla███um ███hio███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...",No Video,1ST███OOR███O 5█████████MAH███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
387,18873142,KETCH,Men Blue Slim Fit Low Distress Heavy Fade Stre...,0.0,0,1849,62.000000,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",S &███Mar███ing███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",No Video,"Sy ███330███324█████████B,3███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
388,18992754,AMERICAN EAGLE OUTFITTERS,Women Grey Straight Fit High-Rise Highly Distr...,4.8,5,4499,60.000000,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_M██████,"[{""size"":""24"",""value"":""24.0in"",""value_name"":""T...",No Video,"Gro███ Fl███, N█████████old███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
389,18973922,Levis,Men Blue 65504 Skinny Fit Mid Rise Light Fade ...,4.1,237,4099,53.503982,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":22,""2_stars"":8,""3_stars"":27,""4_stars...","[{""percentage"":""39"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973922_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
390,18979610,KiddoPanti,Girls Grey No Fade Stretchable Cotton Jeans,3.9,7,1399,52.000000,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Kri███n A███rel█████████Lim██████,"[{""size"":""2-3Y"",""value"":""19.6in"",""value_name"":...",No Video,"Gro███ Fl███, 4█████████n A███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
391,18675392,Jack & Jones,Men Blue Skinny Fit Mildly Distressed Heavy Fa...,3.8,81,3499,50.000000,"""₹1,749.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":16,""2_stars"":5,""3_stars"":3,""4_stars""...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",BES███NIT███IND█████████TS █████████,"[{""size"":""28/30"",""value"":""28.0in"",""value_name""...",No Video,"Lal███Res███ncy█████████or,███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
392,18973950,Levis,65504 Men Navy Blue Skinny Straight Fit Mid-Ri...,4.1,156,4999,51.000000,"""₹2,449.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":20,""2_stars"":5,""3_stars"":10,""4_stars...","[{""percentage"":""70"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973950_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
393,18198558,FOREVER 21,Women Navy Blue Flared Light Fade Wide-leg Jeans,3.7,6,1799,70.000000,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/181...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""24"",""value"":""24.0in"",""value_name"":""T...",No Video,Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",jeans
394,18094702,Roadster,The Lifestyle Co Men Blue Slim Fit Mid-Rise S...,3.9,35,2499,60.000000,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/180...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":5,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Unknown,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18094702_cae700"",""https://videos.myntasse...",Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",jeans
395,19842706,Llak Jeans,Men Black Skinny Fit Light Fade Stretchable Jeans,4.2,9,2299,75.000000,"""₹2,299.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Video,Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",jeans
396,13768634,Nautica,Men Black Slim Fit Stretchable Jeans,4.6,16,4999,53.503982,"""₹4,999.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""88"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...","[""rw-13768634_cae700"",""https://videos.myntasse...",Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",jeans
397,18973700,Levis,Men Blue 511 Slim Fit Heavy Fade Stretchable J...,3.8,116,4699,53.503982,"""₹4,699.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":22,""2_stars"":5,""3_stars"":8,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973700_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
398,18973728,Levis,Men 65504 Skinny Tapered Fit Jeans,4.4,260,4399,47.000000,"""₹4,399.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":18,""2_stars"":6,""3_stars"":13,""4_stars...","[{""percentage"":""82"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973728_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
399,18903330,Levis,Women Blue Skinny Fit High-Rise Stretchable Jeans,4.4,235,3299,20.000000,"""₹1,649.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":13,""2_stars"":4,""3_stars"":16,""4_stars...","[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""25"",""value"":""25.0in"",""value_name"":""T...","[""rw-18903330_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
400,18973740,Levis,Men Blue 512 Slim Tapered Fit Mid Rise Stretch...,4.3,340,4099,57.000000,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":28,""2_stars"":12,""3_stars"":14,""4_star...","[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973740_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,No Variations,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
401,18953840,KETCH,Men Grey Slim Fit Heavy Fade Stretchable Jeans,3.2,24,1899,68.000000,"""₹607.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":4,""2_stars"":3,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",No Video,Plo███o- ███ 1s█████████Sui███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
402,18969982,Allen Solly Junior,Boys Slim Fit Heavy Fade Stretchable Jeans,4.2,6,1799,35.000000,"""₹1,169.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Wes███ry ███din█████████d_M██████,"[{""size"":""2-3Y"",""value"":""19.5in"",""value_name"":...",No Video,"Gro███ Fl███, N█████████old███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
403,18953870,KETCH,Men Charcoal Tapered Fit Light Fade Stretchabl...,3.8,85,1749,62.000000,"""₹682.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":12,""2_stars"":5,""3_stars"":10,""4_stars...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",No Video,Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
404,19017664,Allen Solly Sport,Men Navy Blue Slim Fit Light Fade Jeans,3.9,8,3299,40.000000,"""₹1,979.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",Wes███ry ███din█████████d_M██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Video,"Gro███ Fl███, N█████████old███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
405,18925586,KETCH,Men Charcoal Skinny Fit Mildly Distressed Stre...,3.6,15,1749,62.000000,"""₹649.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":3,""2_stars"":1,""3_stars"":2,""4_stars"":...",No Review,S &███Mar███ing███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",No Video,"Sy ███330███324█████████B,3███████████████████...","[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
406,18734066,Flying Machine,Men Blue Micheal Slim Fit Mid-Rise Light Fade ...,4.1,26,2699,61.000000,"""₹1,052.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":3,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...","[""rw-18734066_cae700"",""https://videos.myntasse...",10T███LOO███DU █████████ITY███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
407,18993370,Blackberrys,Men Navy Blue Slim Fit Stretchable Jeans,4.3,29,3295,40.000000,"""₹1,647.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Fla███tar███mme██████,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Video,"1st███oor███abi█████████02,███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
408,15190770,AMERICAN EAGLE OUTFITTERS,Women Blue Slim Fit High-Rise Light Fade Jeans,4.0,6,3999,60.000000,"""₹1,599.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Wes███ry ███din█████████d_M██████,"[{""size"":""24"",""value"":""24.0in"",""value_name"":""T...",No Video,"Gro███ Fl███, N█████████old███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans

In [23]:
df[df["category"] == "handbags"]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
312,21421856,Baggit,Dinosaur Textured PU Regular Structured Handhe...,4.4,5,1990,50.000000,"""₹796.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Sup███om ███,"[{""size"":""S""}]","[""rw-21421856_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
313,21421918,Baggit,Textured Handheld Bag,4.6,18,1890,46.000000,"""₹1,039.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",No Review,Sup███om ███,"[{""size"":""M""}]","[""rw-21421918_cae700"",""https://videos.myntasse...",Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
314,16696848,Accessorize,London Women Faux Leather Piper Sling bag,4.6,38,4995,61.000000,"""₹1,648.00""",INR,http://assets.myntassets.com/assets/images/166...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-16696848_cae700"",""https://videos.myntasse...",Sho███o. ███-10█████████enu███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
315,21232798,ESTALON,Women PU Bowling Sling Bag,0.0,0,2499,64.000000,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/212...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Men███Bra███Tec█████████ Pr███████████████,"[{""size"":""Onesize""}]",No Video,2nd███oor███O. █████████Lan███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
316,18200086,Caprese,Yellow Structured Shoulder Bag,4.0,59,3699,75.000000,"""₹924.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":4,""2_stars"":5,""3_stars"":6,""4_stars"":...",No Review,Ret███Net███,"[{""size"":""Onesize""}]","[""rw-18200086_cae700"",""https://videos.myntasse...",Blo███B-1███abi█████████-24███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",handbags
317,7743536,Lino Perros,Navy Blue Solid Shoulder Bag,4.5,6,4495,66.000000,"""₹4,495.00""",INR,http://assets.myntassets.com/assets/images/774...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]",No Video,Unavailable,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",handbags
318,7743355,Lino Perros,Blue Solid Shoulder Bag,4.3,14,3495,60.000000,"""₹3,495.00""",INR,http://assets.myntassets.com/assets/images/774...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]","[""rw-7743355_cae700""]",Unavailable,"[{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",handbags
319,8293015,Lychee bags,White Solid Sling Bag,3.9,84,1699,4.000000,"""₹1,699.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":12,""2_stars"":2,""3_stars"":8,""4_stars""...",No Review,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unavailable,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",handbags
320,17637810,Toteteca,Women Black PU Structured Shoulder Bag,4.8,5,3099,63.000000,"""₹3,099.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",handbags
321,17761230,Caprese,Red Leather Structured Shoulder Bag,4.1,10,3999,70.000000,"""₹3,999.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unavailable,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",handbags
322,15188034,Metro,Grey PU Swagger Sling Bag,4.3,10,1290,53.503982,"""₹1,290.00""",INR,http://assets.myntassets.com/assets/images/151...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,MET███BRA███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Met███Bra███ Li█████████ldi███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
323,21762808,Baggit,Structured Sling Bag,4.6,10,1690,50.000000,"""₹845.00""",INR,http://assets.myntassets.com/assets/images/217...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Bag███ In███ Pv██████,"[{""size"":""M""}]","[""https://videos.myntassets.com/assets/videos/...",204███8Na███an █████████van███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
324,21421996,Baggit,Studded Sling Bag,4.5,40,1990,50.000000,"""₹995.00""",INR,http://assets.myntassets.com/assets/images/214...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",No Review,Bag███ In███ Pv██████,"[{""size"":""XXS""}]","[""rw-21421996_cae700"",""https://videos.myntasse...",204███8Na███an █████████van███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
325,21621752,Berrylush,Checked Structured Handheld Bag,4.0,111,3299,59.000000,"""₹1,349.00""",INR,http://assets.myntassets.com/assets/images/216...,...,"{""1_star"":10,""2_stars"":6,""3_stars"":11,""4_stars...",No Review,AJN███S T███ SO█████████RIV████████████,"[{""size"":""Onesize""}]",No Video,"A29███ect███59,█████████udh███████████████████...",No Variations,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
326,13359482,FLYING BERRY,Silver-Toned Solid Handheld Bag,4.9,7,2999,44.000000,"""₹1,679.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Abh███Ove███as ██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",A42███nd ███orO█████████str███████████████████...,"[{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
327,13389422,DailyObjects,Multicoloured Printed Sling Bag,4.3,123,2999,62.000000,"""₹1,139.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":7,""2_stars"":5,""3_stars"":11,""4_stars""...",No Review,Fir███Who███ale█████████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Fi███ Wh███sal█████████ Li███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
328,13389410,DailyObjects,Pink & Beige Printed Sling Bag,4.2,30,2999,62.000000,"""₹1,139.00""",INR,http://assets.myntassets.com/assets/images/133...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":5,""4_stars"":...",No Review,Fir███Who███ale█████████Lim██████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","Plo███o. ███1, █████████foc███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags
329,22603262,DailyObjects,Charcoal Trunk Laptop Tote Bag,3.8,6,3999,25.000000,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",No Review,Fir███Who███ale█████████,"[{""size"":""Onesize""}]",No Video,Fi███ Wh███sal█████████ Li███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",handbags

In [24]:
df.sort_values(by="final_price")

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
525,17292364,Mitera,Mustard & Gold-Toned Striped Zari Leheriya Saree,4.0,18,4199,76.0,"""₹1,007.00""",INR,http://assets.myntassets.com/assets/images/172...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fabric Qual...",AAR███LIF███YLE█████████LIM██████,"[{""size"":""Onesize""}]",No Video,"B-4███,40███402█████████36,███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
665,19024468,Blackberrys,Men Pure Cotton Printed Slim Fit Shorts,4.1,9,1695,40.0,"""₹1,017.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",No Review,Moh███Clo███ng █████████Ltd███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",No Video,C/o███s G███cus█████████hai███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shorts
532,16287654,Saree mall,Navy Blue Floral Linen Blend Banarasi Saree,4.1,359,4099,75.0,"""₹1,024.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":37,""2_stars"":10,""3_stars"":30,""4_star...","[{""percentage"":""50"",""value_name"":""Fabric Quali...",AAR███LIF███YLE█████████LIM████████████,"[{""size"":""Onesize""}]",No Video,"B-4███,40███402█████████36,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sarees
929,10019547,XYXX,Men IntelliSoft Antimicrobial Micro Modal Pack...,4.7,9,1197,14.0,"""₹1,029.00""",INR,http://assets.myntassets.com/assets/images/100...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",XYX███PPA███S P█████████MIT███,"[{""size"":""S"",""value"":""28.0in to 30.0in"",""value...","[""rw-10019547_cae700"",""pi-10019547_cae700""]",406███ 41███SAN█████████ILE███████████████████...,No Variations,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",trunk
248,22411344,Juniper,Floral Embroidered Flared Cotton Midi Dress,3.9,11,4149,75.0,"""₹1,037.00""",INR,http://assets.myntassets.com/assets/images/224...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",No Review,AMA███XPO███ IN█████████AL █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""To...",No Video,G-9███SIT███RA █████████L A███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",ethnic-dresses
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,13638220,FAUSTO,Men Brown Textured Loafers,3.2,6,999,1.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":3,""4_stars"":...","[{""percentage"":""34"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""6"",""value"":""25.5cm"",""value_name"":""To...",No Video,Unavailable,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",casual-shoes
817,18478530,Paralians,White Print peplum Top,3.7,454,999,50.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/184...,...,"{""1_star"":58,""2_stars"":35,""3_stars"":68,""4_star...","[{""percentage"":""59"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""T...",No Video,Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
808,20405594,AAHWAN,White Bralette Crop Top,3.2,166,999,50.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/204...,...,"{""1_star"":47,""2_stars"":13,""3_stars"":24,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",Unknown,"[{""size"":""Onesize"",""value"":""26.0in"",""value_nam...",No Video,Unavailable,"[{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops
201,20195790,Dupatta Bazaar,Sequin Embroidered Net Dupatta,4.7,10,999,48.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/201...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",No Review,Unknown,"[{""size"":""Onesize""}]",No Video,Unavailable,"[{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",dupatta
870,17938374,CODE by Lifestyle,White & Turquoise Blue Floral Print Top,4.4,17,999,30.0,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Unknown,"[{""size"":""XS"",""value"":""30.0in"",""value_name"":""B...",No Video,Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tops

In [25]:
df = df.drop_duplicates()

In [26]:
df["quantity"] = 1

In [27]:
df["total_amount"] = df["final_price"] * df["quantity"]

In [28]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unavailable,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,"""₹3,995.00"""
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unavailable,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,"""₹2,899.00"""
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unavailable,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,"""₹2,999.00"""
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unavailable,No Variations,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,"""₹1,675.00"""
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No Video,Unavailable,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,"""₹2,899.00"""

In [30]:
df.to_csv("cleaned_dataset.csv", index=False)